general:
  output_dir: "./processed_dataset"
  log_level: "INFO"
  plugins_dir: "./plugins"
  recursive: true
  stop_on_error: true

processes:
  move_images:
    rules:
      - name: vision_language_rule
        plugin: moondream2/vision_language_rule
        params:
          model_id: "vikhyatk/moondream2"
          revision: "2024-05-20"
          question: "What is the color of the object?"
          expected_answer: "red"
      - name: similarity_rule
        plugin: deepfakePlugin/similarity_rule
        params:
          threshold: 0.7
          model_name: "VGG-Face"
          distance_metric: "cosine"
          reference_img_path: "./ref_image.jpeg"
          negate: False
      - plugin: image/is_image
        name: isimage
        params:
          allowed_formats:
            - ".jpg"
            - ".jpeg"
            - ".png"
    actions:
      - plugin: io/move
        name: move_images
        params:
          target_dir: "./moved_images"
          dry_run: false  # Set to true for testing without actually moving files
        conditions:
          - is_image
      - plugin: stablediffusion/sdxl_image_generation_action
        name: generate_image
        params:
          prompt: "A cinematic shot of a baby racoon wearing an intricate italian priest robe."
          model_id: "stabilityai/sdxl-turbo"
          output_dir: "./moved_images_new"
          num_inference_steps: 1
          guidance_scale: 0.0
          height: 512
          width: 512
        conditions: [
          similarity_rule
        ]  # No conditions; action will always run
      - plugin: stablediffusion/stable_diffusion_image_generation_action
        name: generate_image2
        params:
          model_id: "runwayml/sahneboy"
          prompt: " a boy with a red hat"
          negative_prompt: "noisy, low quality"
          output_dir: "./generated_images_2"
          guidance_scale: 7.5
          num_inference_steps: 50
          height: 512
          width: 512
          seed: -1
          batch_size: 5
          use_attention_slicing: True
          use_vae_slicing: False
        conditions: [
          isimage
          similarity_rule
          vision_language_rule
        ]  # No conditions; action will always run
  deepfake_process:
    rules:
      - name: similarity_rule
        plugin: deepfakePlugin/similarity_rule
        params:
          threshold: 0.7
          model_name: "VGG-Face"
          distance_metric: "cosine"
          reference_img_path: "./ref_image.jpeg"
          negate: False

    actions:
      - plugin: io/move
        params:
          target_dir: "./moved_imagesss"
          dry_run: false  # Set to true for testing without actually moving files
        conditions:
          - similarity_rule

  stable_diffusion_process:
    rules: [ ]  # No rules are required for this process
    actions:
      - plugin: stablediffusion/stable_diffusion_image_generation_action
        params:
          model_id: "runwayml/stable-diffusion-v1-5"
          prompt: "a futuristic cityscape at sunset with flying cars"
          negative_prompt: "noisy, low quality"
          output_dir: "./generated_images"
          guidance_scale: 7.5
          num_inference_steps: 50
          height: 512
          width: 512
          seed: -1
          batch_size: 5
          use_attention_slicing: True
          use_vae_slicing: False
        conditions: [ ]  # No conditions; action will always run

  xl:
    rules: [ ]  # No rules are required for this process
    actions:
      - plugin: stablediffusion/sdxl_image_generation_action
        params:
          prompt: "A cinematic shot of a baby racoon wearing an intricate italian priest robe."
          model_id: "stabilityai/sdxl-turbo"
          output_dir: "./generated_images_sdxl"
          num_inference_steps: 1
          guidance_scale: 0.0
          height: 512
          width: 512
        conditions: []  # No conditions; action will always run

  vision_language_process:
    rules:
      - name: vision_language_rule
        plugin: moondream2/vision_language_rule
        params:
          model_id: "vikhyatk/moondream2"
          revision: "2024-05-20"
          question: "What is the color of the object?"
          expected_answer: "red"

    actions:
      - name: copy_if_red
        plugin: io/copy
        params:
          target_dir: "./red_objects"
          dry_run: false
        conditions:
          - vision_language_rule

  caption_process:
    rules:
      - name: florence_caption_rule
        plugin: florencePlugin/florence_caption_rule
        params:
          prompt: "Describe this image."

    actions:
      - name: copy_images_with_caption
        plugin: io/copy
        params:
          target_dir: "./captioned_images"
          dry_run: false
        conditions:
          - florence_caption_rule

  blur_faces_process:
    actions:
      - plugin: deepfakePlugin/blur_faces_action
        params:
          blur_factor: 15
          output_dir: "./blurred_faces"